<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.cibseven</groupId>
    <artifactId>release-parent</artifactId>
    <version>1.6.0</version>
    <!-- do not remove empty tag - http://jira.codehaus.org/browse/MNG-4687 -->
    <relativePath />
  </parent>

  <groupId>org.cibseven.bpm</groupId>
  <artifactId>cibseven-root</artifactId>
  <version>2.3.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>CIB seven - Root Pom</name>
  <inceptionYear>2024</inceptionYear>

  <description>
    This pom defines the modules that make up the build.
    The parent pom for all CIB seven projects can be found in the parent directory relative to this file.
  </description>

  <properties>
    <license.includeTransitiveDependencies>false</license.includeTransitiveDependencies>

    <!-- These properties are used in both the BOM as well as camunda-parent and subprojects -->
    <version.mybatis>3.5.15</version.mybatis>
    <version.joda-time>2.12.5</version.joda-time>
    <version.uuid-generator>4.3.0</version.uuid-generator>
    <version.feel-scala>1.22.0</version.feel-scala>
    <version.license-maven-plugin>2.4.0</version.license-maven-plugin>
    <!-- Version for cibseven-webclient-web -->
    <cibseven-webapp.version>${project.version}</cibseven-webapp.version>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>${version.license-maven-plugin}</version>
        <configuration>
          <acceptPomPackaging>true</acceptPomPackaging>
          <excludedScopes>test</excludedScopes>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <!-- distro profile is default and builds the complete distribution.
         Does not run integration tests. -->
    <profile>
      <id>distro</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <!-- This profile is run in the CI as the first step (platform-ASSEMBLY); It must not activate
          any modules that have a dependency to the webapps. See also the referenced POMs,
          they usually define which modules are covered by the distro profile -->
        <module>spring-boot-starter</module>
        <module>spring-boot-4-starter</module>

        <module>quarkus-extension</module>

        <module>qa</module>

        <module>javaee/ejb-service</module>
        <module>javaee/ejb-client</module>
        <module>javaee/ejb-client-jakarta</module>
        <module>javaee/jobexecutor-ra</module>
        <module>javaee/jobexecutor-rar</module>

        <module>model-api</module>
        <module>engine-dmn</module>
        <module>connect</module>
        <module>juel</module>
        <module>spin</module>
        <module>commons</module>
        <module>freemarker-template-engine</module>

        <module>test-utils/testcontainers</module>
        <module>test-utils/junit5-extension</module>
        <module>test-utils/junit5-extension-dmn</module>
        <module>test-utils/assert</module>
        <module>test-utils/archunit</module>

        <module>engine</module>
        <module>engine-cdi</module>
        <module>engine-spring</module>
        <module>engine-rest</module>

        <module>webapps</module>

        <module>examples</module>

        <module>engine-plugins</module>

        <module>distro/license-book</module>
        <module>distro/jboss</module>
        <module>distro/tomcat</module>
        <module>distro/sql-script</module>
        <module>distro/run</module>
        <module>distro/run4</module>

        <module>clients/java</module>

        <module>internal-dependencies</module>
        <module>database</module>
        <module>parent</module>
        <module>bom</module>
      </modules>
    </profile>

    <profile>
      <id>javadocs</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <configuration>
              <failOnError>false</failOnError>
              <additionalJOptions>
                <additionalJOption>-Xdoclint:none</additionalJOption>
                <additionalJOption>--ignore-source-errors</additionalJOption>
                <additionalJOption>--allow-script-in-comments</additionalJOption>
              </additionalJOptions>
              <doctitle>CIB seven Javadocs ${project.version}</doctitle>
              <windowtitle>CIB seven Javadocs ${project.version}</windowtitle>
              <notimestamp>true</notimestamp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>distro-serverless</id>
      <modules>
        <module>qa</module>

        <module>engine</module>
        <module>engine-cdi</module>
        <module>engine-spring</module>
        <module>engine-rest</module>

        <module>webapps</module>

        <module>examples</module>

        <module>engine-plugins</module>

        <module>distro/sql-script</module>

        <module>internal-dependencies</module>
        <module>database</module>
        <module>parent</module>
        <module>bom</module>
      </modules>
    </profile>

    <profile>
      <id>distro-tomcat</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <module>distro/license-book</module>
        <module>distro/tomcat</module>
      </modules>
    </profile>

    <profile>
      <id>distro-wildfly</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <module>javaee/ejb-client</module>
        <module>javaee/ejb-client-jakarta</module>
        <module>distro/license-book</module>
        <module>distro/wildfly</module>
        <module>distro/wildfly28</module>
      </modules>
    </profile>

    <profile>
      <id>distro-webjar</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <module>distro/webjar</module>
      </modules>
    </profile>

    <profile>
      <id>distro-run</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <module>distro/run</module>
        <module>distro/run4</module>
      </modules>
    </profile>

    <profile>
      <!-- profile for running process-engine unit tests in QA -->
      <id>check-engine</id>
      <modules>
        <module>engine</module>
        <module>engine-cdi</module>
        <module>engine-spring</module>
        <module>engine-rest</module>

        <module>internal-dependencies</module>
        <module>database</module>
        <module>parent</module>
        <module>bom</module>
      </modules>
    </profile>

    <profile>
      <!-- profile for running webapp unit tests in QA -->
      <id>check-webapps</id>
      <modules>
        <module>internal-dependencies</module>
        <module>parent</module>
        <module>bom</module>
      </modules>
    </profile>

    <profile>
      <id>sonatype-oss-release</id>
      <modules>
        <module>spring-boot-starter</module>
        <module>spring-boot-4-starter</module>
        <module>quarkus-extension</module>
        <module>model-api</module>

        <module>engine</module>
        <module>engine-cdi</module>
        <module>engine-spring</module>
        <module>engine-rest</module>

        <module>engine-dmn</module>
        <module>connect</module>
        <module>juel</module>
        <module>spin</module>
        <module>commons</module>
        <module>freemarker-template-engine</module>

        <module>javaee/ejb-client</module>
        <module>javaee/ejb-client-jakarta</module>

        <module>webapps</module>

        <module>engine-plugins</module>

        <module>distro/webjar</module>

        <module>clients/java</module>

        <module>test-utils/junit5-extension</module>
        <module>test-utils/junit5-extension-dmn</module>
        <module>test-utils/assert</module>

        <module>internal-dependencies</module>
        <module>database</module>
        <module>parent</module>
        <module>bom</module>
      </modules>
    </profile>

    <profile>
      <id>license-header-check</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.mycila</groupId>
            <artifactId>license-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>

  <repositories>
    <repository>
      <id>mvn-group</id>
      <name>Maven group</name>
      <!-- Links to repos for local builds by community users on master branch,
      for local builds by developers on maintainance branches, jboss and maven central -->
      <url>https://artifacts.cibseven.org/repository/mvn-group</url>
    </repository>
  </repositories>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <organization>
    <name>CIB seven</name>
    <url>https://cibseven.org</url>
  </organization>

  <url>https://cibseven.org</url>

  <developers>
    <developer>
      <id>CIB seven</id>
      <name>CIB seven Community</name>
      <organization>CIB seven</organization>
      <organizationUrl>https://cibseven.org</organizationUrl>
    </developer>
  </developers>

  <scm>
    <url>https://github.com/cibseven/cibseven</url>
    <connection>scm:git:git@github.com:cibseven/cibseven.git</connection>
    <developerConnection>scm:git:git@github.com:cibseven/cibseven.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/cibseven/cibseven/issues</url>
  </issueManagement>

</project>
