name: Renovate auto-merge
on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
jobs:
  all-checks-passed:
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.actor == 'vladgrind'
    name: All checks passed
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: write
      pull-requests: write
    steps:
      - uses: wechuli/allcheckspassed@v1.2.0
